### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by MiraiTunga** [epam/OSCI#51]
when i run the command below 

`python3 osci.py daily-osci-rankings -td 2020-01-02`

i get the following error 

```
Traceback (most recent call last):
  File "osci.py", line 44, in <module>
    from cli import company_rankers
  File "/home/mirai/OSCI/cli/company_rankers.py", line 23, in <module>
    from __app__.jobs.contributors_ranking import ContributorsRankingJob
  File "/home/mirai/OSCI/__app__/jobs/contributors_ranking.py", line 17, in <module>
    from pyspark.sql import DataFrame
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/serializers.py", line 72, in <module>
    from pyspark import cloudpickle
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/mirai/.local/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```
os: Ubuntu 20.04.1 LTS 
python : Python 3.8.5
pip: 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

any ideas whats causing this ?

**Comment by vlad-isayko** [comment]
@MiraiTunga Unfortunately pyspark 2.4.5 does not support python 3.8.

https://stackoverflow.com/questions/58700384/how-to-fix-typeerror-an-integer-is-required-got-type-bytes-error-when-tryin
https://issues.apache.org/jira/browse/SPARK-29536

There are two options left to either downgrade the python version or upgrade to the pyspark> = 3.0 version. 

Now our team is doing tests before the update to spark 3.
